//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoProyectosASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        public decimal codigo { get; set; }
        public Nullable<decimal> codigo_tarea { get; set; }
        public string codigo_usuario { get; set; }
    
        public virtual Tarea Tarea { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
